#ifndef PINCONFIG
#define PINCONFIG

#include <Arduino.h>

#define PIN_MOTOR_FWD1 GPIO_NUM_20
#define PIN_MOTOR_REV1 GPIO_NUM_21
#define PIN_MOTOR_FWD2 GPIO_NUM_1
#define PIN_MOTOR_REV2 GPIO_NUM_0

#define CHANNEL_MOTOR_FWD1 3
#define CHANNEL_MOTOR_REV1 4
#define CHANNEL_MOTOR_FWD2 5
#define CHANNEL_MOTOR_REV2 6

#define INPUT_DIODE 22


#define PIN_OPTDIOD1 GPIO_NUM_5



#endif