#ifndef PINCONFIG
#define PINCONFIG

#include <Arduino.h>

#define PIN_MOTOR_FWD1 GPIO_NUM_20
#define PIN_MOTOR_REV1 GPIO_NUM_21
#define PIN_MOTOR_FWD2 GPIO_NUM_1
#define PIN_MOTOR_REV2 GPIO_NUM_0

#define CHANNEL_MOTOR_FWD1 2
#define CHANNEL_MOTOR_REV1 3
#define CHANNEL_MOTOR_FWD2 4
#define CHANNEL_MOTOR_REV2 5

#define INPUT_DIODE 22


#define PIN_OPTDIOD_mot_1 GPIO_NUM_5
#define PIN_OPTDIOD_mot_2 GPIO_NUM_6
#define PIN_OPTDIOD_start GPIO_NUM_3
#define PIN_COULEUR GPIO_NUM_7


#endif